"""
apply_readme_architecture.py -- regenerate Section 1 of README.md from the
block specification in make_architecture_figure.py, with verified anchors.

Section 1 of README.md still describes the Campaign 3 layout (13 files).
This applier replaces everything between the heading
"## 1. Repository contents" and the heading "## 2. Requirements" with the
nine-block description and the per-block tables, so README, appendix and
figure come from one specification.

Runs on any machine with Python 3.8+. No OpenMC, no conda, no Graphviz.
Run it from the repository root (~/master-thesis-unipi on wks720).

Usage:
    python apply_readme_architecture.py --check     # report only, change nothing
    python apply_readme_architecture.py             # apply, keeps README.md.bak
    python apply_readme_architecture.py --revert    # restore README.md.bak

Flags:
    --check    verify the two anchors and report APPLIED / READY / MISMATCH
    --revert   copy README.md.bak back over README.md
    --diff     print a unified diff instead of writing (implies --check)
"""

import argparse
import difflib
import platform
import shutil
import sys
from pathlib import Path

README = Path("README.md")
BACKUP = Path("README.md.bak")
ANCHOR_START = "## 1. Repository contents\n"
ANCHOR_END = "## 2. Requirements\n"
MARKER = "<!-- generated by apply_readme_architecture.py -->"

NEW_SECTION_HEAD = """## 1. Repository contents

""" + MARKER + """

The code is organised in nine blocks, drawn in `code_architecture.png`
(generated by `make_architecture_figure.py`, which also prints the tables
below with `--table md`). Only the scripts that compute a physics or
optimisation quantity are listed. Patch scripts (`apply_*.py`, `fix_*.py`,
`repair_*.py`), shell wrappers, figure generators, log parsers and
diagnostics are omitted on purpose. Run
`python make_architecture_figure.py --check` to verify this section
against the tree.

![Macro architecture of the code](code_architecture.png)

Unlabelled arrows are Python imports. Labelled arrows name the file, or
the pair of vectors, exchanged. The central artefact is
`optimization_checkpoint.json`, written by the optimiser at the end of
every block of iterations and read by every confirmation and
post-processing script.

Environment: conda `openmc-env` (`environment.yml`, `Dockerfile`),
OpenMC 0.15.3, ENDF/B-VII.1 cross sections and `chain_endfb71_pwr.xml`
installed once per machine by `setup_data.sh`, resolved through
`OPENMC_CROSS_SECTIONS` and `OPENMC_CHAIN_FILE`.
"""


def machine_check():
    print(f"host : {platform.node()}")
    print(f"cwd  : {Path.cwd()}")
    if not README.exists() or not Path("run_optimization.py").exists():
        print("ABORT: run this from the repository root (README.md and "
              "run_optimization.py must be present).")
        sys.exit(1)
    print()


def build_section() -> str:
    try:
        import make_architecture_figure as spec
    except ImportError:
        print("ABORT: make_architecture_figure.py not found next to this script.")
        sys.exit(1)
    return NEW_SECTION_HEAD + spec.tables_text("md") + "\n---\n\n"


def locate(text: str):
    i = text.find(ANCHOR_START)
    j = text.find(ANCHOR_END)
    if i < 0 or j < 0 or j < i:
        return None
    return i, j


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--revert", action="store_true")
    ap.add_argument("--diff", action="store_true")
    a = ap.parse_args()
    machine_check()

    if a.revert:
        if not BACKUP.exists():
            print("nothing to revert: README.md.bak not found")
            sys.exit(1)
        shutil.copy2(BACKUP, README)
        print("reverted README.md from README.md.bak")
        return

    text = README.read_text(encoding="utf-8")
    span = locate(text)
    if span is None:
        print("MISMATCH: anchors not found (expected '## 1. Repository contents' "
              "before '## 2. Requirements'). Nothing changed.")
        sys.exit(1)
    i, j = span
    old_section = text[i:j]
    new_section = build_section()
    state = "APPLIED" if MARKER in old_section else "READY"
    print(f"anchors ok, section 1 spans {old_section.count(chr(10))} lines, state: {state}")

    if a.diff or a.check:
        if a.diff:
            for line in difflib.unified_diff(old_section.splitlines(), new_section.splitlines(),
                                             "README.md (current)", "README.md (new)", lineterm=""):
                print(line)
        return

    if state == "APPLIED" and old_section == new_section:
        print("already up to date, nothing written")
        return
    shutil.copy2(README, BACKUP)
    README.write_text(text[:i] + new_section + text[j:], encoding="utf-8")
    print(f"wrote README.md ({new_section.count(chr(10))} lines in section 1), backup in README.md.bak")


if __name__ == "__main__":
    main()
